image: golang:1.16.4

cache:
  key: FeelsKappa
  paths:
    - build/go/

stages:
  - build

build:
  stage: build
  script:
    - GOPATH=$PWD/build/go make;
    - GOPATH=$PWD/build/go GOOS=windows make;
    - cd build; tar zcf remiliascarlet.tar.gz remiliascarlet remiliascarlet; cd ../
  artifacts:
    paths:
      - build/remiliascarlet
    expire_in: 1 week
